replicaCount: 1
image:
  repository: nginx
  tag: "1.27.0"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
containerPort: 80
release:
  marker: "v2"
probes:
  readinessPath: /
  livenessPath: /
