apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "next-k8s-admin.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "next-k8s-admin.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: next-k8s-admin
    app.kubernetes.io/managed-by: argocd
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "next-k8s-admin.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "next-k8s-admin.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        gitops.release/version: {{ .Values.release.marker | quote }}
    spec:
      containers:
        - name: {{ include "next-k8s-admin.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readinessPath }}
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.livenessPath }}
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
