apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ljluestc/next-k8s-admin
    targetRevision: private/feature/auth-oidc
    path: deploy/apps/platform-argocd
    helm:
      releaseName: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ljluestc/next-k8s-admin
    targetRevision: private/feature/auth-oidc
    path: deploy/apps/platform-monitoring
    helm:
      releaseName: prometheus
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
