apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ljluestc/next-k8s-admin
    targetRevision: private/feature/auth-oidc
    path: deploy/apps/platform-argocd
    helm:
      releaseName: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-istio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ljluestc/next-k8s-admin
    targetRevision: private/feature/auth-oidc
    path: deploy/apps/platform-istio
    helm:
      releaseName: istio
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istiod-default-validator
      jsonPointers:
        - /webhooks
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istio-validator-istio-system
      jsonPointers:
        - /webhooks
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-tracing
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ljluestc/next-k8s-admin
    targetRevision: private/feature/auth-oidc
    path: deploy/apps/platform-tracing
    helm:
      releaseName: jaeger
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ljluestc/next-k8s-admin
    targetRevision: private/feature/auth-oidc
    path: deploy/apps/platform-monitoring
    helm:
      releaseName: prometheus
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
